### ISSUE TITLE
An pip install error

### ISSUE THREAD

**Issue by fsted** [shuuchen/DetCo.pytorch#5]
Hi，Thank you for the code，But An error occurred when I installed：
ERROR: Could not install packages due to an OSError: [Errno 2] There is no such file or directory: '/home/conda/feedstock_root/build_artifacts/cffi_1600276415718/work'
Do I need to create this folder?

**Comment by shuuchen** [comment]
Hi, 
I don't know about your environment. Could you paste the whole message here ?
