### ISSUE TITLE
want to ask about your training machine

### ISSUE THREAD

**Issue by lenka844** [shuuchen/DetCo.pytorch#7]
Hi, thanks for your brilliant work, but i have some questions about this work when i try to reproduce it, my device is 1070tiX4, the storage is 8G,but when i set the batch-size to 4, it still have the error said that CUDA out of memory. i'm confused whether it's normal or i made something wrong?

**Comment by shuuchen** [comment]
Hi,

I recommend you reduce the batchsize, because detco is memory consuming. 
However, detco is only for multi-gpu environment due to batch shuffling issue.

**Comment by lenka844** [comment]
> Hi, Thanks for your reply. I have already set the batch-size to 4, but it still remind me "CUDA out of memory", i guess it's becaus my devices' storage are too small to run detco, even i have aleady use 4 gpu, thanks again for your reply.
